### ISSUE TITLE
Swipe gesture support?

### ISSUE THREAD

**Issue by Ambient-Impact** [vmitsaras/js-offcanvas#12]
Hi there. I've been looking around for an accessible off canvas that also supports swipe gestures, but that seems to be difficult to find. Is there any chance gestures may be added to js-offcanvas at some point? Currently, I'm planning to retrofit accessibility stuff onto [Snap.js](https://github.com/jakiestfu/Snap.js), which seems to be very good on the gesture front, but really poor with accessibility, but I'd much rather use a solution built from the ground up with accessibility in mind.

**Comment by vmitsaras** [comment]
Hi,

the simpliest solution is to use a external touch-plugin:
https://hammerjs.github.io/ 
https://github.com/mattbryson/TouchSwipe-Jquery-Plugin 
```js
$(function() {      
      //Enable swiping...
      $("#your-swipe-area").swipe( {
       swipeRight:function() {
          $('.js-offcanvas-left').open();  
        },
       swipeLeft:function() {
          $('.js-offcanvas-left').close();  
        }
      });
 });
```
i'll create a pen for this soon

**Comment by Ambient-Impact** [comment]
Those seem like a good start, but I'm hoping for something more tightly integrated. The thing I really like about Snap.js and similar libraries is the way they slide the menu in real time as you swipe, instead of just popping open or closed.

**Comment by vasikgreif** [comment]
Same here, would be cool to see support for this included.

**Comment by vmitsaras** [comment]
Sorry, i can't add Swipe gesture. 
Please use a use a external touch-plugin
See: https://github.com/vmitsaras/js-offcanvas/issues/12#issuecomment-361898617
