### ISSUE TITLE
Swipe up/down auto close menu

### ISSUE THREAD

**Issue by ngoncom** [vmitsaras/js-offcanvas#13]
Hi,

I've tested your example page: http://offcanvas.vasilis.co/examples.html on Samsung Galaxy S6,
open menu and try swipe up/down inside menu content, menu auto close.

- How to prevent menu auto close especially when menu have long content
- Is there any option to fix content not scroll up/down when scroll inside menu

Thank!

P/S: I've tested by add webkit prefix to your js-offcanvas.css by using https://autoprefixer.github.io/ and seem menu not auto close on mobile, could you review js-offcanvas.css?

**Comment by vmitsaras** [comment]
For auto-close on mobile check #14

**Comment by ngoncom** [comment]
Hi Vasileios,

It seem option "resize: false" fixed menu auto close,

$('#my_id').offcanvas({
     modifiers: 'left',
     resize: false
});

but if (modifiers: 'left,reveal') problem still remain, with this I  can swipe right / left to close/open menu and the black area appear, so I have to tap to screen to close the black area.

Thank for your time!

**Comment by vmitsaras** [comment]
A Demo-Link would be helpful

**Comment by ngoncom** [comment]
I've sent you a tweet, thank you!
