### ISSUE TITLE
Usage without Modernizr / build for Modernizr

### ISSUE THREAD

**Issue by CptMeatball** [vmitsaras/js-offcanvas#17]
On of the deps of this project is Modernizr, which on itself is not a problem. But what features of Modernzir are used? I don't use Modernizr in my project, and I dpn't want to use the entire Modernzir build.

Alternatively, is there a way to use OffCanvas without Modernizr? I'm trying to use the normal minified files (not the pkgd ones), which throws an error

```TypeError: e is undefined```

**Comment by vmitsaras** [comment]
You need olny
* prefixed
* transitions
~5KB

``` js
// Grunt Config
{
  "crawl": false,
  "customTests": [],
  "dest": "/PATH/TO/modernizr-output.js",
  "tests": [
    "prefixed"
  ],
  "options": [
    "prefixed",
    "setClasses"
  ],
  "uglify": true
}

//Command Line Config
{
  "minify": true,
  "options": [
    "prefixed",
    "setClasses"
  ],
  "feature-detects": [
    "test/css/transitions"
  ]
}
```

In the pkgd are several necessary helper functions [grunt/concat.js](https://github.com/vmitsaras/js-offcanvas/blob/master/grunt/config/concat.js#L12) like: 
* [utils](https://github.com/vmitsaras/js-utils)
* [trap-tab](https://github.com/vmitsaras/js-trap-tab)
* [button](https://github.com/vmitsaras/js-button)

**Comment by vmitsaras** [comment]
I'll drop the Modernizr Dependency
https://github.com/vmitsaras/js-utils/tree/drop-modernizr

**Comment by vmitsaras** [comment]
Hi @CptMeatball 
can you confirm that this is working?

**Comment by CptMeatball** [comment]
I can confirm that on our project `js-offcanvas.pkgd.min.js` works without modernizr. 

Cheers mate! 🎉
