### ISSUE TITLE
is-open class is not removing on resize window

### ISSUE THREAD

**Issue by googoling** [vmitsaras/js-offcanvas#26]

**Comment by vmitsaras** [comment]
hey,
I need more info.
codepen?
are u using the latest version?
which browser?

**Comment by googoling** [comment]
Yes, I am using the latest version and downloaded from here. It seems in all browser (I've tasted on latest firefox and chrome). 

Please check the link below for a screenshot: 
http://prntscr.com/jmht2f

1. The main menu restored
2. Nav item has gone from the canvas 
3. is-open is still there. 

Thank you

**Comment by vmitsaras** [comment]
default option resize is false
set it to true

**Comment by googoling** [comment]
Should it be something like this: http://prntscr.com/jmn6hs

I tried this but no luck.

**Comment by vmitsaras** [comment]
Hi @googoling 
sorry for the late response.

I'd removed the raf from utils.
Added back to js-offcanvas
can you confirm?
https://github.com/vmitsaras/js-offcanvas/blob/26-close-on-resize-event/dist/_js/js-offcanvas.pkgd.min.js
