### ISSUE TITLE
Offcanvas.close not working in safari

### ISSUE THREAD

**Issue by pavlito** [vmitsaras/js-offcanvas#3]
Hi,

I am using this plugin, but problem occurs in safari.
I have event on click which calss dataOffcanvas.close(). That is not working on safari, works fine on chrome.

Also I have tested http://offcanvas.vasilis.co , and also i demo when you click outside aside element , that is not triggering close method.

**Comment by vmitsaras** [comment]
[prefix.zip](https://github.com/vmitsaras/js-offcanvas/files/949862/prefix.zip)
Safari doesn't support prefixed-free transform and transition.
