### ISSUE TITLE
Problem with Css Modifier Class

### ISSUE THREAD

**Issue by staggattack** [vmitsaras/js-offcanvas#39]
Css modifier class "overlay" is not set correctly on the element "c-offcanvas". It will come out to "c-offcanvas-- overlay" instead of "c-offcanvas--overlay". Thus some important styles aren't applied to this element. Same issue with the element "c-offcanvas-bg".

**Comment by vmitsaras** [comment]
What's your Plugin configuration (options) ?
Initialization through HTML or Javascript?
Example Code would be helpful.

**Comment by staggattack** [comment]
latest version intalled via yarn add js-offcanvas

Initalized through Javascript with simple configuration:
 $('#offCanvas').offcanvas({
        modifiers: 'left, overlay', // default options
        triggerButton: '#triggerButton' // btn to open offcanvas
    });

**Comment by vmitsaras** [comment]
Quick fix
``` js 
modifiers: 'left, overlay', // options: "left"," overlay"
modifiers: 'left,overlay', // <- use this! options without space
```
