### ISSUE TITLE
Inconsistencies between Website Demo/Guide and the Github

### ISSUE THREAD

**Issue by GeorgeWL** [vmitsaras/js-offcanvas#4]
On the Website the only listed Dependencies are:
- jQuery
- Modernizr

On the Github the listed Dependencies are: 
- jQuery
- Modernizr
- js-utils
- js-trap-tab
- js-button

Which is it then?
@vmitsaras

**Comment by lrtr** [comment]
I also found an issue with the documentation. When initializing with jQuery you also need to add the class "js-offcanvas-trigger" to the trigger button. This isn't documented clearly enough.

**Comment by GeorgeWL** [comment]
@lrtr I'd say make it a seperate issue tbh.

**Comment by lrtr** [comment]
From my view it's all connected, the documentation in general isn't that great.
Now to your issue, I think it's only jQuery and Modernizr, if you use "js-offcanvas.pkgd.js" then the other three dependencies seem to be already included.

**Comment by NuclearMachine** [comment]
this application has a very confusing documentation or atleast not instructed properly

**Comment by GeorgeWL** [comment]
@vmitsaras It's a great library based on your demo...but it's so badly documented that it's not going to get many users if its not cleaned up.

please spend the time to cleanup the documentation and heck, why not refactor whilst you're at it?

**Comment by vmitsaras** [comment]
Hey Guys, thanks for the Feedback.
Please check the updated documentation.
