### ISSUE TITLE
 Uncaught TypeError: Cannot read property 'addEventListener' of undefined

### ISSUE THREAD

**Issue by facine** [vmitsaras/js-offcanvas#46]
Hi, thanks for this great plugin!

I'm trying to develop a Drupal contrib module and I get this error only using reveal, with overlay and push works fine.

**This works:**
`&lt;a class="js-offcanvas-trigger"
    data-offcanvas-trigger="off-canvas-id"
    href="#off-canvas">Menu&lt;/a>

&lt;div class="js-offcanvas"
       data-offcanvas-options='{"modifiers": "right,push"}' 
       id="off-canvas-id">...&lt;/div>`

**This isn't work:**
`&lt;a class="js-offcanvas-trigger"
    data-offcanvas-trigger="off-canvas-id"
    href="#off-canvas">Menu&lt;/a>

&lt;div class="js-offcanvas"
       data-offcanvas-options='{"modifiers": "right,reveal"}' 
       id="off-canvas-id">...&lt;/div>
`

**Error message**
js-offcanvas.pkgd.js?v=1.x:89 Uncaught TypeError: Cannot read property 'addEventListener' of undefined
    at Object.utils.onEndTransition (js-offcanvas.pkgd.js?v=1.x:89)
    at window.componentNamespace.Offcanvas.Offcanvas.open (js-offcanvas.pkgd.js?v=1.x:591)
    at window.componentNamespace.Offcanvas.Offcanvas.toggle (js-offcanvas.pkgd.js?v=1.x:692)
    at toggleOffcanvas (js-offcanvas.pkgd.js?v=1.x:857)
    at HTMLAnchorElement.<anonymous> (js-offcanvas.pkgd.js?v=1.x:56)
    at HTMLAnchorElement.dispatch (jquery.min.js?v=3.2.1:3)
    at HTMLAnchorElement.q.handle (jquery.min.js?v=3.2.1:3)

Any idea?
Thanks!

**Comment by vmitsaras** [comment]
HI @facine ,
did you added the offcanvas.css with the reveal css-classes?

**Comment by facine** [comment]
Yes @vmitsaras, these are the loaded files:

![Captura de pantalla 2019-09-17 a las 15 13 36](https://user-images.githubusercontent.com/78108/65044725-c7df5900-d95d-11e9-971d-ad1f18b302e0.png)


And this other de HTML code after open/close the push & reveal elements:
![61kce8ych1no8lt33yep](https://user-images.githubusercontent.com/78108/65044779-de85b000-d95d-11e9-9bbb-083973582b6e.png)

And these are the reveal errors:
![Captura de pantalla 2019-09-17 a las 15 15 38](https://user-images.githubusercontent.com/78108/65044868-0bd25e00-d95e-11e9-8681-870aa1d98f8b.png)

**Comment by facine** [comment]
There wasn't any c-offcanvas-content-wrap, sorry.

after add the wrapper it works fine.

thanks.
