### ISSUE TITLE
Prevent to close the offcanvas

### ISSUE THREAD

**Issue by facine** [vmitsaras/js-offcanvas#47]
Is possible to disable ESC key to close the offcanvas?

I've tried this:
`$(document).off(‘keyup.offcanvas’);`

Thanks

**Comment by vmitsaras** [comment]
hi @facine,

i can't add a Option to disable the ESC to close.
But i've added a workaround.

can you test it if this works and let me know
https://github.com/vmitsaras/js-offcanvas/blob/47-escape-keyup/dist/_js/js-offcanvas.pkgd.js

```js

  $( document ).on( "open.offcanvas", function(){    
    $(document).off('keyup.offcanvas');
  });
``` 

Thanks

**Comment by facine** [comment]
It works fine!

Thanks!
