### ISSUE TITLE
First project not working

### ISSUE THREAD

**Issue by lcsqlpete** [vmitsaras/js-offcanvas#50]
Just downloaded and set everything up using the Codepen example.  I see the Left button and the para text I put in the aside display immediately on page load and clicking the button does nothing.  No console error and the css and js files are where they're supposed to be. 

Help please, html is below.  This on OSX Catalina running Chrome.

`<html>

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Offcanvas</title>
        <link rel="stylesheet" href="https://cdn.kleenedge.com/dev/css/js-offcanvas.css">
    </head>

    <body>

        <main class="c-offcanvas-content-wrap" role="main">
            <button class="c-button js-offcanvas-trigger" data-offcanvas-trigger="off-canvas-left">Left</button>
        </main>

        
        <aside class="js-offcanvas" id="off-canvas-left" role="complementary"><p>Here it is!</p></aside>

        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <script src="https://cdn.kleenedge.com/dev/js/js-offcanvas.pkgd.js"</script>
        <script>
            $(function () {
                $(document).trigger("enhance");
            });
        </script>

    </body>
</html>`

**Comment by vmitsaras** [comment]
Hi @lcsqlpete 

you missed a closing tag (>)
```html
 <script src="https://cdn.kleenedge.com/dev/js/js-offcanvas.pkgd.js"</script>
```
```html
 <script src="https://cdn.kleenedge.com/dev/js/js-offcanvas.pkgd.js"></script>
```

**Comment by lcsqlpete** [comment]
Duh! Sorry to bother you, that fixed it.

*Sent with Shift
<https://tryshift.com/?utm_source=SentWithShift&utm_campaign=Sent%20with%20Shift%20Signature&utm_medium=Email%20Signature&utm_content=General%20Email%20Group>*
