### ISSUE TITLE
js-Offcanvas inside div

### ISSUE THREAD

**Issue by jquimera** [vmitsaras/js-offcanvas#6]
First, this is the best thing I found on github this year.

It would be possible to put the off-canvas inside a div, in a boxed layout. Similar to the example I made in the image below?

![js-offcanvas](https://i.imgur.com/LHa0wQ9.jpg)

Can someone help me? Thank you.

**Comment by vmitsaras** [comment]
Thanks
check the example: https://codepen.io/vmitsaras/full/wrLePg/

**Comment by jquimera** [comment]
@vmitsaras This is perfect. That's exactly it. Thank you very much. ;)
