### ISSUE TITLE
Uncaught TypeError: $(...).offcanvas is not a function

### ISSUE THREAD

**Issue by mburakerman** [vmitsaras/js-offcanvas#9]
Simple demo gives TypeError.

[**JsFiddle**](https://jsfiddle.net/fc9uu3nx/)

**Comment by vmitsaras** [comment]
Modernizr is required and use the latest version
Demo updated:
[https://jsfiddle.net/fc9uu3nx/2/](https://jsfiddle.net/fc9uu3nx/2/)
